### ISSUE TITLE
Need help with curl request

### ISSUE THREAD

**Issue by DanP27** [JobDoesburg/homebridge-mhi-wfrac#1]
how do i do this, from what device? (desktop or iphone)

**Comment by DanP27** [comment]
please can you help guide me through the process

**Comment by JobDoesburg** [comment]
Of course! `curl` is a command line tool you can use to send specific web requests. You should run it from a desktop (or basically, any device in your network), by opening your terminal / command prompt.

The homebridge web interface also provides a terminal by the way! If you click the menu button on the top right of the homebridge web interface, you can open a terminal. And run the curl command from there.

As listed, you will need to know the IP address and device name of your air conditioner. Do you know these?

Let me know if you need more help!

**Comment by DanP27** [comment]
thanks for your reply!

I can try it in the homebridge terminal, didnt think of that.

I have the IP, what would the device name be? The one my Wifi AP has it?
The one i've called it in the app? Or something else?

**Comment by JobDoesburg** [comment]
> what would the device name be?

It's the name of the device in the app after you first installed it. It looks something like "e8165600c13b" (for me, at least).

Let me know if you can't find it, because there are ways to discover it (but they are a bit more complex)

**Comment by JobDoesburg** [comment]
You shouldn't use the airconID as operatorID, but you should use one of the ID's from the `remoteList`. 

The `curl` should return something like:

```json
{
    "command": "getAirconStat",
    "apiVer": "1.0",
    "operatorId": "12345",
    "deviceId": "e8165610d23f",
    "timestamp": 1722259820,
    "result": 1,
    "contents": {
        "airconId": "e8165610d23f",
        "airconStat": "AADqj6//AAAAAIAQCwAAAAAAAf/////F5IEESAcvsQAAiAAAAAEAAAAAAAOAILH/gBDV/5QQAQDZAw==",
        "logStat": 0,
        "updatedBy": "e8165610d23f",
        "expires": 1722547921,
        "ledStat": 1,
        "autoHeating": 0,
        "highTemp": "AB",
        "lowTemp": "66",
        "firmType": "WF-RAC",
        "wireless": {
            "firmVer": "010"
        },
        "mcu": {
            "firmVer": "131"
        },
        "timezone": "Europe/Amsterdam",
        "remoteList": [
            "F691DD55-0975-4C56-AED0-15DCD40FB9E3",
            "",
            "",
            ""
        ],
        "numOfAccount": 1
    }
}
```



In which case the `operatorID` to configure should be `F691DD55-0975-4C56-AED0-15DCD40FB9E3`

Did you do that?

**Comment by DanP27** [comment]
i have used the remote list id now and it seems to be working, thank you!

**Comment by JobDoesburg** [comment]
Great!
